services:
  - type: web
    name: pos-crono-demo
    env: docker
    context: Backend
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: PORT
        value: 8080
